### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by AngelCrawford** [AngelCrawford/blog#179]
- Es gibt eine SEO Desc, welche unterschiedlich von der Summary ist
- Summary
  - Wird aus dem Content generiert, ohne Header, Links und Co
  - Sollte IMMER vorhanden sein, nicht optional
  - Ausgabe mit Bold, italic und anderen einfachen Markdown Designs erlauben in der Card, aber nur in dem selbst geschriebenen Summary
  - Summary ist NICHT optional!

---
``` yaml
---
# Archetype article.md
title: ''  # Required field, initially empty
date: {{ .Date }}
draft: true
description: '' # Required field
---
```

```go
/* /layouts/_default/single.html */
{{ if not .Params.title }}
    {{ errorf "Missing title in front matter for page: %s" .File.Path }}
{{ end }}
```
If a required field is missing, you can use errorf to output an error message during site build, or use printf to display a message on the rendered page. 

Or use this .html part as a Shortcode, if more then one use.
