### ISSUE TITLE
Details information on single Post

### ISSUE THREAD

**Issue by AngelCrawford** [AngelCrawford/blog#39]
- [x] Zum Frontmatter ein `icons` hinzufügen
- [x] Anzeigen in einem Artikel unter dem Bereich "Details" (siehe Bild)
```yaml
icons:
- src: "fab fa-windows"
  color: "#456987"
- src: "fab fa-linux"
  color: "#123456"
```
---
- [x] Shortcode für den weiteren Bereich von Details, mit Tags Design umsetzen
```yaml
{{ details "detail-überschrift" "liste, der, details, die, umgesetzt, werden, sollen" }}
```

![73391539-7619e880-42d8-11ea-8950-bca9774379c4](https://user-images.githubusercontent.com/16148683/76218464-919bdb80-6214-11ea-915b-f22bcee3b561.png)
