### ISSUE TITLE
Merge and Deploy

### ISSUE THREAD

**Issue by AngelCrawford** [AngelCrawford/blog#67]
- [ ] https://gohugo.io/host-and-deploy/host-on-github-pages/

---

- [ ] Webhook einrichten der den merged Branch wieder löscht
  * https://www.gabescode.com/staticman/2019/01/04/staticman-comments-for-jekyll.html#webhook
- [ ] Domain erstellen, auf die nachher deployed werden soll
  - [ ] Domain in `staticman.yml` eintragen `allowedOrigins: ["localhost", "example.com"]`
  - [ ] Domain in `config.toml` eintragen `baseURL`
- [ ] Ich möchte erneut Github Pages verwenden
  * Dieses Repo ist mein "gesamter Code"-Repo
  * Unter "[blog-public](https://github.com/AngelCrawford/blog-public)" befindet sich der fertig kompilierte public?

## Github Actions
- [ ] Bilder verkleinern mit Github Actions: https://css-tricks.com/optimize-images-with-a-github-action/
- [ ] Github Actions einrichten, damit ein Merge ebenfalls `hugo` als Befehl ausführt und die Seite neu baut
  * Anleitung: https://chringel.dev/2022/05/automatically-deploy-a-hugo-website-to-a-remote-host-using-github-actions/
  - [ ] https://github.com/peaceiris/actions-hugo
  - [ ] So werden Kommentare auch direkt online gebracht ⇒ Testen
  * Nachdem das Repo erstellt wurde, die Github Actions Datei erstellen
  - [ ] Git Tag in Actions: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-git-tag

## Quellen
- Lokale Deploy Datei und Tutorial: https://gist.github.com/AngelCrawford/06dbd50beee9f96064b8dc1d71dfa120
  - Die Deploy Datei funktioniert nur in der Git Bash!

```yml
name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.12
        with:
          hugo-version: '0.74.3'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
```

Erweiterung von #1
